
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwhhgizprlbjwcplaxiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3aGhnaXpwcmxiandjcGxheGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDIzNDgsImV4cCI6MjA1ODAxODM0OH0.cqCThcU9xZdBLAvez6CqtZ9ZkCEZDjv7DH1EEf1AbLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Add a listener to detect auth changes but don't reload the page
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Supabase auth event:', event);
  // Do not force page refresh on auth changes
});

